AllCops:
  NewCops: enable
  Exclude:
    - "Guardfile"
    - "Rakefile"
    - "node_modules/**/*"

  DisplayCopNames: true

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 50

Metrics/ClassLength:
  Max: 150

Metrics/BlockLength:
  Max: 30

Layout/HashAlignment:
  EnforcedColonStyle: key

Layout/ExtraSpacing:
  AllowForAlignment: false

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Lint/RaiseException: {}

Lint/StructNewOverride: {}

Style/HashEachMethods: {}

Style/HashTransformKeys: {}

Style/HashTransformValues: {}
